"""user authentication

Revision ID: 43242c50d6d1
Revises: 9eacf96298b9
Create Date: 2019-07-31 18:24:22.973632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43242c50d6d1'
down_revision = '9eacf96298b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
